### ISSUE TITLE
Downloaded file doesn't populate Phase number

### ISSUE THREAD

**Issue by arapawa** [dannytpeck/luminous-shard#2]
Every downloaded filename is
Client-Phase--2018.csv
instead of
Client-Phase-1-2018.csv
Client-Phase-1B-2018.csv
etc.

e.g.,
![filenames](https://user-images.githubusercontent.com/16523445/35528288-462a1202-04e2-11e8-86ca-8f8107d2c1a4.png)

**Comment by dannytpeck** [comment]
Resolved in https://github.com/dannytpeck/luminous-shard/commit/971b2d602261430796567a40519678a7eee74f26
